# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * auth_brute_force
#
# Translators:
# OCA Transbot <transbot@odoo-community.org>, 2017
# Pedro M. Baeza <pedro.baeza@gmail.com>, 2017
# enjolras <yo@miguelrevilla.com>, 2018
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 10.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-02 18:39+0000\n"
"PO-Revision-Date: 2018-03-02 18:39+0000\n"
"Last-Translator: enjolras <yo@miguelrevilla.com>, 2018\n"
"Language-Team: Spanish (https://www.transifex.com/oca/teams/23907/es/)\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_form
msgid "Add remote to whitelist"
msgstr ""

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_authentication_attempt
#: model:ir.ui.menu,name:auth_brute_force.menu_res_authentication_attempt
msgid "Authentication Attempts"
msgstr "Intentos de autenticación"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_result
msgid "Authentication Result"
msgstr "Resultado de la autenticación"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
msgid "Banned"
msgstr "Bloqueado"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_create_uid
msgid "Created by"
msgstr "Creado por"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_create_date
msgid "Created on"
msgstr "Creado el"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_display_name
msgid "Display Name"
msgstr "Nombre a mostrar"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
msgid "Failed"
msgstr "Fallido"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_id
msgid "ID"
msgstr "ID"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt___last_update
msgid "Last Modified on"
msgstr "Última actualización por"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_write_uid
msgid "Last Updated by"
msgstr "Última actualización por"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_write_date
msgid "Last Updated on"
msgstr "Última actualización el"

#. module: auth_brute_force
#: model:ir.model.fields,help:auth_brute_force.field_res_authentication_attempt_remote_metadata
msgid "Metadata publicly available for remote IP"
msgstr ""

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_remote
#, fuzzy
msgid "Remote IP"
msgstr "ID remoto"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_remote_metadata
msgid "Remote IP metadata"
msgstr ""

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_form
msgid "Remove remote from whitelist"
msgstr ""

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
msgid "Successful"
msgstr "Existoso"

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_login
msgid "Tried Login"
msgstr ""

#. module: auth_brute_force
#: model:ir.model,name:auth_brute_force.model_res_users
msgid "Users"
msgstr ""

#. module: auth_brute_force
#: model:ir.model.fields,field_description:auth_brute_force.field_res_authentication_attempt_whitelisted
msgid "Whitelisted"
msgstr ""

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.view_res_authentication_attempt_search
msgid "Without Success"
msgstr "Sin éxito"

#. module: auth_brute_force
#: model:ir.model,name:auth_brute_force.model_res_authentication_attempt
msgid "res.authentication.attempt"
msgstr "res.authentication.attempt"

#~ msgid "Active"
#~ msgstr "Activo"

#~ msgid "Attempt Date"
#~ msgstr "Fecha de intento"

#~ msgid "Attempts"
#~ msgstr "Intentos"

#~ msgid "Ban Date"
#~ msgstr "Fecha de bloqueo"

#~ msgid "Banned Remotes"
#~ msgstr "Remotos bloqueados"

#~ msgid "Description"
#~ msgstr "Descripción"

#~ msgid "Successfull"
#~ msgstr "Existoso"

#~ msgid "Uncheck this box to unban the remote"
#~ msgstr "Desmarque esta casilla para desbloquear el remoto"

#~ msgid "res.banned.remote"
#~ msgstr "res.banned.remote"

#. module: auth_brute_force
#: code:addons/auth_brute_force/controllers/main.py:23
#, python-format
msgid "The maximun number of tries have been reached. The %s has been banned. Please contact with the service administrator."
msgstr "El número máximo de intentos ha sido alcanzado. El %s ha sido bloqueado. Póngase en contacto con su administrador de servicio."

#. module: auth_brute_force
#: code:addons/auth_brute_force/controllers/main.py:23
#, python-format
msgid "user"
msgstr "usuario"

#. module: auth_brute_force
#: code:addons/auth_brute_force/controllers/main.py:23
#, python-format
msgid "remote"
msgstr "IP"

#. module: auth_brute_force
#: model:ir.model.fields,help:auth_brute_force.field_res_users_is_banned
msgid "Technical field to compute if user is banned by reach max attempts of failed logins"
msgstr "Campo técnico para calcular si el usuario ha alcanzado el número máximo de intentos fallidos y ha sido bloqueado"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.auth_brute_force_view_users_form
msgid "Unblock user"
msgstr "Desbloquear usuario"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.auth_brute_force_view_users_form
msgid "Reset failed attempts of this user in order to be able to login again"
msgstr "Elimina los intentos fallidos de éste usuario y lo habilita para iniciar sesión nuevamente"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.auth_brute_force_view_users_form
msgid "Open login records"
msgstr "Abrir registros de inicio de sesión"

#. module: auth_brute_force
#: model:ir.ui.view,arch_db:auth_brute_force.auth_brute_force_view_users_form
msgid "Open view of login attempts filtered by active user"
msgstr "Abre la vista de inicios de sesión filtrada por el usuario actual"

#. module: auth_brute_force
#: code:addons/auth_brute_force/controllers/main.py:23
#, python-format
msgid "Could not reset your password. The user has been banned. Please contact with the service administrator."
msgstr "No se puede restablecer la contraseña. El usuario ha sido bloqueado. Póngase en contacto con su administrador de servicio."